# This file is for documentation and IDE support
# The actual toolchain is managed by Nix/fenix in flake.nix
[toolchain]
channel = "stable"
components = ["rustfmt", "clippy", "rust-src", "rust-analyzer"]
profile = "default"