# ExternalMetricSource indicates how to scale on a metric not associated with any Kubernetes object (for example length of queue in cloud messaging service, or QPS from loadbalancer running outside of cluster).
{
  metric | optional | MetricIdentifier | doc "metric identifies the target metric by name and selector",
  target | optional | MetricTarget | doc "target specifies the target value for the given metric",
}
